<a href="https://colab.research.google.com/github/ajaykumar080286/MachineLearning1/blob/main/glab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

from sklearn.datasets import load_diabetes

import matplotlib.pyplot as plt


In [ ]:
X,y=load_diabetes(return_X_y=True)

In [ ]:
y.shape

(442,)

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,SGDRegressor
from sklearn.metrics import r2_score

In [ ]:
X_train,X_test, y_train,y_test=train_test_split(X,y,test_size=0.2, random_state=2)

In [ ]:
lr=LinearRegression()

In [ ]:
lr.fit(X_train, y_train)

LinearRegression()

In [ ]:
lr.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [ ]:
lr.intercept_

np.float64(151.88331005254167)

In [ ]:
r2_score(y_test, lr.predict(X_test))

0.4399338661568968

In [ ]:
sgd=SGDRegressor(max_iter=20, learning_rate='constant', eta0=0.1)

In [ ]:
batch_size=35

for i in range(100):

  idx=random.sample(range(X_train.shape[0]),batch_size)

  sgd.partial_fit(X_train[idx], y_train[idx])


sgd.coef_
sgd.intercept_


array([160.38579002])

In [ ]:
sgd.coef_

array([  27.59438963, -201.38319676,  527.41113976,  327.58657285,
        -57.69510273, -118.09808153, -192.2294704 ,   86.65245449,
        475.74655247,   84.21333344])

In [ ]:
sgd.intercept_

array([160.38579002])

In [ ]:
print(r2_score(y_test,sgd.predict(X_test)))
import random

0.4412202095898531


In [ ]:
from numpy.ma import shape
class ownBatchRegressor:

  def __init__(self,lr,epochs,bs):
    self.intercept_=None
    self.coef_=None
    self.lr=lr
    self.epochs=epochs
    self.bs=bs

  def fit(self,X_train,y_train):

    # calculation of intercept

    self.intercept_=0
    self.coef_=np.ones(X_train.shape[1])
    batc_size=int(X_train.shape[0]/self.bs)
    print(batc_size)

    for i in range(self.epochs):
      for j in range(int(X_train.shape[0]/self.bs)):


            idx = random.sample(range(X_train.shape[0]), batc_size)

            y_hat=np.dot(X_train[idx],self.coef_)+self.intercept_
            der_slope=-2*np.mean(y_train[idx]-y_hat)
            self.intercept_=self.intercept_ -(self.lr*der_slope)
            # coef
            der_coef_slope=-2*np.dot((y_train[idx]-y_hat),X_train[idx])
            self.coef_=self.coef_- self.lr*der_coef_slope

    print(self.intercept_)
    print(self.coef_)

  def predict(self,X_test):
    return np.dot(X_test,self.coef_)+self.intercept_

In [ ]:
batch=ownBatchRegressor(0.1,20,10)

In [ ]:
batch.fit(X_train,y_train)

35
153.73423355831338
[ -24.27296818 -222.06648101  528.82073264  337.21540602  -84.46352702
  -74.84128141 -181.57956702   84.40325866  555.76698983   58.70052815]


In [ ]:
X_train.shape

(353, 10)

In [ ]:
r2_score(y_test,batch.predict(X_test))

0.44481635218308246

In [ ]:
np.ones(X_train.shape[0]).shape

(353,)

In [ ]:
np.ones(X_train.shape[1]).shape

(10,)

In [ ]:

idx = np.random.randint(0, X_train.shape[0])
X_train[idx].shape

(10,)

In [ ]:
idx

8