<a href="https://colab.research.google.com/github/ajaykumar080286/MachineLearning1/blob/main/MeraRidgeMultiDim.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_diabetes

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge, SGDRegressor
from sklearn.metrics import mean_squared_error,r2_score



In [ ]:
X,y= load_diabetes(return_X_y=True)

X_train,X_test, y_train, y_test= train_test_split(X,y, test_size=0.2, random_state=4)

In [ ]:
reg=SGDRegressor(penalty='l2', max_iter=500, eta0=0.1,learning_rate='constant',alpha=0.001)

In [ ]:
reg.fit(X_train,y_train)

SGDRegressor(alpha=0.001, eta0=0.1, learning_rate='constant', max_iter=500)

In [ ]:
reg.coef_

array([ 5.03136549e+01, -1.48015720e+02,  3.59632881e+02,  2.65301332e+02,
        3.21864862e-01, -5.28914635e+01, -1.67491602e+02,  1.40127129e+02,
        3.24874699e+02,  1.03016361e+02])

In [ ]:
reg.intercept_

array([144.11934564])

In [ ]:
r2_score(y_test,reg.predict(X_test))

0.43112567804733837

In [ ]:
rr=Ridge(alpha=0.001, max_iter=500, solver='sparse_cg')

In [ ]:
rr.fit(X_train,y_train)
print(r2_score(y_test,rr.predict(X_test)))


0.46250101619914563


In [ ]:
print(rr.coef_)
print(rr.intercept_)

[  34.52192544 -290.84084076  482.40181344  368.0678662  -852.44873179
  501.59160336  180.11115788  270.76333979  759.73534372   37.4913546 ]
151.10198517439466


In [ ]:
class MeraRidge:

  def __init__(self,epochs,lr,alpha):
    self.lr=lr
    self.epochs=epochs
    self.alpha=alpha
    self.coef_=None
    self.intercept_=None

  def fit(self,X_train, y_train):

      self.coef_=np.ones(X_train.shape[1])
      self.intercept_=0
      theta=np.insert(self.coef_,0,self.intercept_)
      X_train=np.insert(X_train,0,1,axis=1)


      for i in range(self.epochs):
        der_Slope=   np.dot(X_train.T,X_train).dot(theta)-np.dot(X_train.T,y_train)+self.alpha*theta
        theta = theta-self.lr*der_Slope


      self.coef_=theta[1:]
      self.intercept_=theta[0]

  def predict(self,X_test):
    return np.dot(X_test,self.coef_)+self.intercept_

In [ ]:
reg = MeraRidge(epochs=500,alpha=0.001,lr=0.005)


In [ ]:
reg.fit(X_train,y_train)

In [ ]:
reg.coef_

array([  46.65050914, -221.3750037 ,  452.12080647,  325.54248128,
        -29.09464178,  -96.47517735, -190.90017011,  146.32900372,
        400.80267299,   95.09048094])

In [ ]:
reg.intercept_

np.float64(150.86975316713472)

In [ ]:
r2_score(y_test,reg.predict(X_test))

0.4738018280260913